-- A serial column past 90% of integer, and an integer foreign key to a bigint key past 70%.
CREATE TABLE fixture_orders (id serial PRIMARY KEY);
SELECT setval('fixture_orders_id_seq', 2000000000);
CREATE TABLE fixture_invoices (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
SELECT setval(pg_get_serial_sequence('fixture_invoices', 'id'), 1500000000);
CREATE TABLE fixture_payments (invoice_id int REFERENCES fixture_invoices (id));
-- As pgcheckup grant prints it, so the check can read the counters.
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO checkup;
