-- The same high counters, on bigint columns all the way through.
CREATE TABLE fixture_orders (id bigserial PRIMARY KEY);
SELECT setval('fixture_orders_id_seq', 2000000000);
CREATE TABLE fixture_invoices (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
SELECT setval(pg_get_serial_sequence('fixture_invoices', 'id'), 1500000000);
CREATE TABLE fixture_payments (invoice_id bigint REFERENCES fixture_invoices (id));
-- As pgcheckup grant prints it, so the check can read the counters.
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO checkup;
