<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Pgcheckup\Pgcheckup.csproj" />
    <ProjectReference Include="..\..\src\Pgcheckup.Checks.Generator\Pgcheckup.Checks.Generator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\checks\**\fixtures\*.sql" LinkBase="checks" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
