using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Pgcheckup.Checks.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class CheckGenerator : IIncrementalGenerator
{
    private const string ChecksDirProperty = "build_property.PgcheckupChecksDir";

    private static readonly DiagnosticDescriptor InvalidCheck = new(
        "PGC001", "Invalid check", "{0}", "pgcheckup", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoChecksDir = new(
        "PGC002", "Checks folder not set", "{0}", "pgcheckup", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var root = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
            options.GlobalOptions.TryGetValue(ChecksDirProperty, out var dir) && !string.IsNullOrWhiteSpace(dir)
                ? Normalize(dir).TrimEnd('/') + "/"
                : null);

        var files = context.AdditionalTextsProvider
            .Combine(root)
            .Where(pair => pair.Right != null && Normalize(pair.Left.Path).StartsWith(pair.Right, StringComparison.OrdinalIgnoreCase))
            .Select((pair, cancellationToken) =>
            {
                var relative = Normalize(pair.Left.Path).Substring(pair.Right!.Length);
                var needsText = relative.EndsWith("/" + CheckCompiler.CheckMd, StringComparison.Ordinal)
                    || relative.EndsWith("/" + CheckCompiler.CheckSqlFile, StringComparison.Ordinal);
                return new CheckFile(pair.Left.Path, relative, needsText ? pair.Left.GetText(cancellationToken)?.ToString() : null);
            })
            .Collect();

        context.RegisterSourceOutput(files.Combine(root), static (spc, input) => Emit(spc, input.Left, input.Right));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<CheckFile> files, string? root)
    {
        if (root == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(NoChecksDir, Location.None, "Set the PgcheckupChecksDir MSBuild property to the checks folder."));
            return;
        }

        var compiled = new List<CompiledCheck>();
        foreach (var folder in files.Where(f => f.Relative.Contains("/")).GroupBy(f => f.Relative.Substring(0, f.Relative.IndexOf('/'))).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            string? Text(string name) => folder.FirstOrDefault(f => f.Relative == folder.Key + "/" + name)?.Text;

            var others = folder.Select(f => f.Relative.Substring(folder.Key.Length + 1)).ToList();
            var compilation = CheckCompiler.Compile(new CheckFiles(folder.Key, Text(CheckCompiler.CheckMd), Text(CheckCompiler.CheckSqlFile), others));
            foreach (var error in compilation.Errors)
            {
                var path = root + folder.Key + "/" + error.File;
                var position = new LinePosition(Math.Max(0, error.Line - 1), 0);
                var location = Location.Create(path, default, new LinePositionSpan(position, position));
                context.ReportDiagnostic(Diagnostic.Create(InvalidCheck, location, $"{folder.Key}: {error.Message}"));
            }

            if (compilation.Check != null)
            {
                compiled.Add(compilation.Check);
            }
        }

        context.AddSource("CheckCatalog.g.cs", Source(compiled));
    }

    private static string Source(IReadOnlyList<CompiledCheck> checks)
    {
        const string ns = "global::Pgcheckup.Checks.";
        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine("namespace Pgcheckup.Checks;");
        code.AppendLine();
        code.AppendLine("internal static partial class CheckCatalog");
        code.AppendLine("{");
        code.AppendLine($"    public static global::System.Collections.Generic.IReadOnlyList<{ns}CheckDefinition> All {{ get; }} = new {ns}CheckDefinition[]");
        code.AppendLine("    {");
        foreach (var check in checks)
        {
            code.AppendLine($"        new {ns}CheckDefinition(");
            code.AppendLine($"            Id: {Literal(check.Id)},");
            code.AppendLine($"            Title: {Literal(check.Title)},");
            code.AppendLine($"            Category: {Literal(check.Category)},");
            code.AppendLine($"            Severity: {ns}Severity.{Pascal(check.Severity)},");
            code.AppendLine($"            MinVersion: {check.MinVersion.ToString(CultureInfo.InvariantCulture)},");
            code.AppendLine($"            Privileges: new string[] {{ {string.Join(", ", check.Privileges.Select(Literal))} }},");
            code.AppendLine($"            SkipOn: new string[] {{ {string.Join(", ", check.SkipOn.Select(Literal))} }},");
            code.AppendLine($"            Thresholds: new {ns}Threshold[] {{ {string.Join(", ", check.Thresholds.Select(t => $"new {ns}Threshold({Literal(t.Name)}, {ns}ThresholdKind.{t.Value.Kind}, {t.Value.Value.ToString(CultureInfo.InvariantCulture)}m, {Literal(t.Value.Text)})"))} }},");
            code.AppendLine($"            Sql: {Literal(check.Sql)},");
            code.AppendLine($"            Message: new {ns}Template({Parts(check.Message)}),");
            code.AppendLine($"            Fix: new {ns}Template({Parts(check.Fix)}),");
            code.AppendLine($"            Note: {Literal(check.Note)}),");
        }

        code.AppendLine("    };");
        code.AppendLine("}");
        return code.ToString();

        static string Parts(IEnumerable<TemplatePart> parts) =>
            $"new {ns}TemplatePart[] {{ {string.Join(", ", parts.Select(Part))} }}";

        static string Part(TemplatePart part) => part switch
        {
            TextPart t => $"new {ns}TextPart({Literal(t.Text)})",
            ValuePart v => $"new {ns}ValuePart({Literal(v.Name)}, {ns}ValueFormat.{(v.Format == null ? "Default" : Pascal(v.Format))})",
            SectionPart s => $"new {ns}SectionPart({Parts(s.Parts)})",
            _ => throw new InvalidOperationException(),
        };
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Pascal(string value) => char.ToUpperInvariant(value[0]) + value.Substring(1);

    private static string Normalize(string path) => path.Replace('\\', '/');

    private sealed record CheckFile(string Path, string Relative, string? Text);
}
